### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by SRechenberger** [SRechenberger/pi-board#1]
# Implement features for version 1.0.0
## User Management
  - [x] Register new user
  - [x] Login as user
  - [x] Modify profile
    - [x] Set displayed name (username/handle shall be fixed)
    - [x] Simple optional message
    - [x] Set profile pic
## Administration
  - [ ] User roles (Admin, Moderator) #18
### Admin
  - [ ] Delete Users #19
  - [ ] Delete Posts (from all boards) #20
  - [ ] Create Boards #17
  - [ ] Make users admins and moderators #21
### Moderator
  - [ ] Delete Posts (from specific boards) #23
  - [ ] Make users moderators (over the board they moderate) #22
## Posts (all in plain text; on a central board)
  - [x] Central board #10
  - [x] Write new posts
  - [x] Edit posts #5 
  - [x] Delete post #6 
  - [ ] Add pictures/files #7 
  - [x] Comment on posts
  - [x] Comment on comments
  - [ ] *ACK*-button for posts ("acknowledged": feedback like a "like" but much less retarded) #8 
## Additional issues
  - [x] #3 
  - [x] #11
  - [x] #12
  - [x] #13 
  - [ ] #14
  - [x] #15
  - [x] #16
